import { test } from 'node:test';
import assert from 'node:assert/strict';
import net from 'node:net';
import path from 'node:path';
import { isolateHome, makeRepo, useFakeAgent, clearFakeAgent, until, BUDGET } from '../helpers.js';
import { addProject } from '../../src/registry.js';
import { startServer } from '../../src/server.js';
import { openPage } from '../browser.js';

test('Board Agent UI persists user choice, executes routine work, and approves concrete exceptions', async (t) => {
  isolateHome(); useFakeAgent(); t.after(clearFakeAgent);
  const repo = makeRepo(); addProject(repo); const name = path.basename(repo);
  const page = await openPage(); if (!page) return t.skip('Chrome unavailable');
  t.after(() => page.close());
  const port = await new Promise((resolve) => { const s = net.createServer(); s.listen(0, '127.0.0.1', () => { const p = s.address().port; s.close(() => resolve(p)); }); });
  const server = await startServer({ port }); t.after(() => server.close());
  await page.goto(`http://127.0.0.1:${port}/?token=${server.token}&project=${encodeURIComponent(name)}`);
  await until(async () => await page.eval(`document.querySelectorAll('.column').length > 0`), { timeout: BUDGET.stage });
  await page.eval(`document.getElementById('board-agent-open').click()`);
  await until(async () => await page.eval(`document.querySelectorAll('#ba-boards input').length > 0`), { timeout: BUDGET.quick });
  await page.eval(`document.querySelector('#ba-boards input').checked = true; document.querySelector('#ba-permissions input[value="pause_queue"]').checked = true; document.getElementById('ba-settings').requestSubmit()`);
  await until(async () => await page.eval(`document.getElementById('ba-history').textContent.includes('rules updated')`), { timeout: BUDGET.quick });
  await page.eval(`document.getElementById('ba-text').value = 'Review my boards'; document.getElementById('ba-message').requestSubmit()`);
  await until(async () => await page.eval(`document.getElementById('ba-history').textContent.includes('Your selected boards are ready')`), { timeout: BUDGET.stage });
  await page.eval(`document.getElementById('ba-contact').value = 'external'; document.getElementById('ba-contact').dispatchEvent(new Event('change')); document.getElementById('ba-settings').requestSubmit()`);
  await until(async () => await page.eval(`document.getElementById('ba-status').textContent.includes('External agent')`), { timeout: BUDGET.quick });
  assert.equal(await page.eval(`document.getElementById('ba-external').hidden`), false);
  const action = async (body) => (await fetch(`http://127.0.0.1:${port}/api/board-agent/actions`, { method: 'POST', headers: { 'x-todomd-token': server.token }, body: JSON.stringify(body) })).json();
  assert.equal((await action({ action: 'pause_queue', project: name, request_id: 'ui-pause' })).ok, true);
  const proposal = await action({ action: 'create_card', project: name, request_id: 'ui-create', title: 'A title: safely quoted', description: '<img src=x onerror=alert(1)>', why: 'User asked for this follow-up' });
  assert.ok(proposal.pending);
  await until(async () => await page.eval(`document.querySelectorAll('#ba-pending button').length === 2`), { timeout: BUDGET.quick });
  assert.equal(await page.eval(`document.querySelectorAll('#ba-pending img').length`), 0);
  assert.match(await page.eval(`document.getElementById('ba-pending').textContent`), /A title: safely quoted/);
  await page.eval(`document.querySelector('#ba-pending button').click()`);
  await until(async () => await page.eval(`document.getElementById('ba-history').textContent.includes('create_card — accepted by board')`), { timeout: BUDGET.quick });
  await page.eval(`document.getElementById('ba-close').click(); document.getElementById('board-agent-open').click()`);
  await until(async () => await page.eval(`document.getElementById('ba-contact').value === 'external'`), { timeout: BUDGET.quick });
  assert.equal(await page.eval(`document.querySelector('#ba-boards input').checked`), true);
  assert.deepEqual(page.errors, []);
});
